name: example-environment
channels:
  - conda-forge
dependencies:
  - python==3.8.5
  - numpy
  - pip
  - altair
  - altair_saver
  - nodejs
  - numpy
  - scipy
  - matplotlib
  - s3fs
  - papermill
  - geoalchemy2
  - openpyxl
  - cartopy
  - scikit-learn
  - geopandas
  - intake
  - intake-parquet
  - pyarrow
  - python-snappy
  - pip:
    - flake8
    - intake-dcat
    - intake-geopandas
    - jupyterlab>=1.0a3
    - descartes
    - folium
    - python-dotenv