name: simple-coronavirus-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyterlab=1.0
  - numpy
  - pandas>=1.0
  - numpy
  - pip
  - altair
  - altair_saver
  - nodejs
  - numpy
  - scipy
  - matplotlib
  - s3fs
  - papermill
  - geoalchemy2
  - openpyxl
  - cartopy
  - scikit-learn
  - geopandas
  - intake
  - intake-parquet
  - pyarrow
  - python-snappy
  - pip:
    - flake8
    - intake-dcat
    - intake-geopandas
    - descartes
    - folium
    - python-dotenv