---
font: Lato
fontsize: 10pt
geometry: left=1in,right=1in,top=0.35in,bottom=0.6in
header-includes: \input{preamble.tex}
output:
  html_document: default
  pdf_document: default
sansfont: Lato
urlcolor: null
params:
  county: "Los Angeles"
  start_date: "2020-04-15"
---

\raggedright


```{r rmarkdown-setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(dev = "cairo_pdf")
options(knitr.kable.NA = "")
options(kableExtra.latex.load_packages = FALSE)

# Knit RMarkdown
library(knitr)

# Tables
library(kableExtra)

# Data Cleaning pipeline
library(tidyverse)
library(dplyr)
library(scales) # formatting numbers
library(arrow) # read parquets
library(zoo) # moving averages
library(reshape2)

# Plotting
library(ggplot2)
library(ggthemes)
library(plotly) #interactive charts
library(htmltools) #for ggplotly to work with loop
```


```{r import-data}

us_county<-arrow::read_parquet("../data/us-county-time-series.parquet", as_tibble=TRUE)
ca_hospitalizations<-read.csv("https://raw.githubusercontent.com/CityOfLosAngeles/covid19-indicators/master/data/ca-hospital-and-surge-capacity.csv")

# Call parameters from our utils files
source("../notebooks/r_utils.R")
YESTERDAY_DATE <-YESTERDAY_DATE
TWO_WEEKS_AGO <- TWO_WEEKS_AGO


# Call parameters from utils files
source("../notebooks/r_chart_utils.R")
# Chart parameters
NAVY<-NAVY
MAROON<- MAROON
LIGHT_GRAY<-LIGHT_GRAY
```


```{r chart-functions, echo=FALSE, out.width=c("50%", "50%")}

plot_charts <- function(df, county, start_date, chart_type="cases"){
  source("../notebooks/r_utils.R")
  
  cases_df <- prep_county(df, county, start_date)
  
  source("../notebooks/r_chart_utils.R")
  
  
  if (chart_type=="cases"){
    # Adjust chart title to show county name
    #chart_title = paste(county, "County: New Cases")

    chart_html<-plotCasesHTML(cases_df, 
                  chart_title=""
                  )
      
    }

  if (chart_type=="deaths"){
    # Adjust chart title to show county name
    #chart_title = paste(county, "County: New Deaths")

    chart_html<-plotDeathsHTML(cases_df, 
                  chart_title=""
                  )
    }
  
  return(chart_html)
  }

```


```{r make-charts, echo = FALSE, results = 'asis'}
county_list = c("Alameda", "Los Angeles")

# Loop makes ggplotly disappear as output
# https://github.com/ropensci/plotly/issues/570
plotlist = list()

for (c in county_list) {

    cases_chart <- plot_charts(us_county, c, params$start_date, "cases") 
    
    deaths_chart <- plot_charts(us_county, c, params$start_date, "deaths") 
    
    # Options for side-by-side
    #https://stackoverflow.com/questions/1249548/side-by-side-plots-with-ggplot2
    #Cleanest ex: https://github.com/ropensci/plotly/issues/570
    
    
    #If we use subplot, then chart can only have 1 title
    # Each subplot must use annotation to get its own title
    #https://stackoverflow.com/questions/45200544/title-of-subplots-in-plotly
    chart <- subplot(cases_chart, deaths_chart) %>% 
      layout(title = paste(c, "County: New Cases and New Deaths"))

    plotlist[[c]] = ggplotly(chart)
    
}
htmltools::tagList(setNames(plotlist, NULL))


```


```{r , echo = FALSE}

#As of `r YESTERDAY_DATE`, there have been `r comma(subset_df$cases)` cumulative cases and `r #comma(subset_df$deaths)` cumulative deaths in `r params$county` County.

#https://stackoverflow.com/questions/38733403/edit-labels-in-tooltip-for-plotly-maps-using-ggplot2-in-r
```

