---
font: Lato
fontsize: 10pt
geometry: left=1in,right=1in,top=0.35in,bottom=0.6in
header-includes: \input{preamble.tex}
output:
  pdf_document: default
  word_document: default
  html_document:
sansfont: Lato
urlcolor: null
params:
  county: "Los Angeles"
  start_date: "2020-07-01"
---

\raggedright


```{r rmarkdown-setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(dev = "cairo_pdf")
options(knitr.kable.NA = "")
options(kableExtra.latex.load_packages = FALSE)

# Knit RMarkdown
library(knitr)

# Tables
library(kableExtra)

# Data Cleaning pipeline
library(tidyverse)
library(dplyr)
library(scales) # formatting numbers
library(arrow) # read parquets
library(zoo) # moving averages
library(reshape2)

# Plotting
library(ggplot2)
library(ggthemes)

```


```{r import-data}

us_county<-read_parquet("../data/us-county-time-series.parquet", as_tibble = TRUE)
ca_hospitalizations<-read.csv("../data/ca-hospital-and-surge-capacity.csv")

YESTERDAY_DATE <- format(Sys.Date()-1,"%Y-%m-%d")
TWO_WEEKS_AGO <- format(Sys.Date()-15, "%Y-%m-%d")

# Chart parameters
NAVY<-"#0A4C6A"
MAROON<- "#F3324C"
LIGHT_GRAY<-"#EAEBEB"

```


```{r select-parameter, echo = FALSE}

source("r_utils.R")

cases <- prep_county(us_county, params$county, params$start_date)

hospitalizations <-prep_hospital(ca_hospitalizations, params$county, params$start_date)

```


```{r plot-cases-deaths, echo=FALSE}
#https://stackoverflow.com/questions/5106782/use-of-ggplot-within-another-function-in-r
plotCasesDeaths<-function(df, y_var, line_color, chart_title, ytitle){
  
  arg <- match.call()
  
  chart <- ggplot(df, 
            aes(x = date, 
                y = eval(arg$y_var)
                )) +
  labs(x = "date", 
       y = eval(arg$ytitle), 
       title=eval(arg$chart_title)) + 
  geom_line(colour=eval(arg$line_color)) +
  geom_area(data = df %>% subset(date >= TWO_WEEKS_AGO),
            fill = LIGHT_GRAY) +
    #Draw a line again otherwise the shading removes some of the line
  geom_line(colour=eval(arg$line_color)) +
  scale_color_fivethirtyeight() +
  scale_x_date(date_labels = "%m-%d", 
               date_breaks = "2 weeks") +
  theme_minimal() +
  theme(legend.position="none", 
        )
  
  return(chart)
}


# Plot cases / deaths
plotCasesDeaths(cases, y_var=new_cases_avg7, 
                line_color=NAVY, 
                chart_title="New Cases: 7-day avg", 
                ytitle="daily new cases")

plotCasesDeaths(cases, y_var=new_deaths_avg7, 
                line_color=MAROON, 
                chart_title="New Deaths: 7-day avg", 
                ytitle="daily new deaths")

```


```{r county-cases, echo=FALSE}
```

### Cases and Deaths by Neighborhood

The charts below look at total cases and deaths in `r params$neighborhood`. Data over the past week for `r params$neighborhood` is shown below:


```{r old1, echo=FALSE, eval=FALSE}
# arbitrary data to demonstrate a table
#today_date = sys.Date()
data <- read.csv(file = "../data/la-county-neighborhood-time-series.csv", 
                 header = TRUE, sep = ",", row.names(FALSE))

data$date <- as.Date(factor(data$date))

# Add new_cases and new_deaths columns
neighborhood_df <- filter(data, Region == params$neighborhood) %>% 
  mutate(
    new_cases = cases - lag(cases), 
    new_deaths = deaths - lag(deaths),
    ) 

#sapply(data, class)

past_week <- neighborhood_df %>% 
  select(c("Region", "date", "cases", "deaths")) %>%
  tail(n=7) 



# Print table of past week
kable(past_week, format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                position = "center", full_width = F) %>%
  column_spec(1, bold = T, border_right = T) %>%
  row_spec(0, bold = T)
```


```{r old2, echo=FALSE, eval=FALSE}
CASE_TITLE = "{params$neighborhood}: Total Cases"
DEATH_TITLE = "{params$neighborhood}: Total Deaths"

chart_aesthetics <- function(chart) {
  chart <- chart +
        theme(
          plot.title = element_text(family = "Roboto", face = "bold", color = "#797C7C", 
                                    size = 10, hjust=0.5), 
          axis.title.x = element_text(size = 9), 
          axis.title.y = element_text(size=9), 
          axis.text.x = element_text(size=8)
          ) +
        scale_x_date(labels = date_format("%m-%d"), breaks = date_breaks("2 weeks")
        ) 
  
  return(chart)
}
```
This chart shows total cases over time.

```{r old3, echo=FALSE, eval=FALSE,  fig.width=6 , fig.height=4}
# Cases chart
cases_chart <- ggplot() + 
      geom_line(
        aes(y = cases, x = date), data = neighborhood_df, color = "#0A4C6A") +
        xlab("date") + ylab("# cumulative cases") + 
        ggtitle(glue(CASE_TITLE))

cases_chart <- chart_aesthetics(cases_chart) %>% ggplotly()
cases_chart
```

This chart shows total deaths over time (deaths data was collected by neighborhoods starting mid-July).

```{r old4, echo=FALSE, eval=FALSE, fig.width=6, fig.height=4}
# Deaths chart
deaths_chart <- ggplot() + 
      geom_line(
        aes(y = deaths, x = date), 
        data = filter(neighborhood_df, date >= '2020-07-01'), 
        color = "#F3324C") +
        xlab("date") + ylab("# cumulative deaths") + 
        ggtitle(glue(DEATH_TITLE))

deaths_chart <- chart_aesthetics(deaths_chart) %>% ggplotly()
deaths_chart
```
